pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: master
        feature: .+
    github:
      credentials:
        description: primary GitHub clone/checkout
  branches:
    feature:
      - cmake:
          cmake:
            cMakeDir: '.'
          make:
            makeDir: '.'
    master:
      - cmake:
          make:
            makeDir: '.'
