pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: master
        feature: .+
    cPlusPlus:
      dockerImage: derekisinternet/opencv-test:0.3.0
    github:
      credentials:
        description: primary GitHub clone/checkout
      uri: "https://github.com/derekisinternet/RoboVision"
    jenkins:
      workflows: 
        branch: v0.5.0
        repo: 'https://github.com/concur/jenkins-workflows'
        credentials: 
          description: primary GitHub clone/checkout
    tests:
      dockerImage: derekisinternet/opencv-test:0.2.0
      executable: roboVision
      imageSetDir: "${env.IMAGE_DIRECTORY}"
      positiveSet: hands
      negativeSet: negatives
  branches:
    feature:
      steps:
        - tests:
          - test:

    master:
      steps:
        - cPlusPlus:
          - make:
              makeDir: 'app/build'
