pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: master
        feature: .+
    github:
      credentials:
        description: primary GitHub clone/checkout
    cMake:
      container: robovision_test
  branches:
    feature:
      steps:
        - docker:
            build:
              dockerfile: Dockerfile
              name: robovision_test
        - cMake:
            cMake:
              cMakeDir: 'app/build'
              cMakeLists: CMakeLists.txt
            make:
              makeDir: 'app/build'
    master:
      steps:
        - cmake:
            make:
              makeDir: 'app/build'
