pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: master
        feature: .+
    cPlusPlus:
      container: derekisinternet/opencv-test:0.1.0
    github:
      credentials:
        description: primary GitHub clone/checkout
      uri: "https://github.com/derekisinternet/RoboVision"
    jenkins:
      workflows: 
        branch: v0.5.0
        repo: 'https://github.com/concur/jenkins-workflows'
        credentials: 
          description: primary GitHub clone/checkout
    tests:
      executable: app/build/roboVision
      positiveSet: hand
      negativeSet: negatives
  branches:
    feature:
      steps:
        - cPlusPlus:
          - cMake:
              cMakeBuildDir: /app/build
          - make:
              makeDir: build
        - tests:
          - test:

    master:
      steps:
        - cPlusPlus:
          - make:
              makeDir: 'app/build'
